import { Project, Category } from "@/types";

export const demoCategories: Category[] = [
  { id: "1", name: "Fotografía", slug: "fotografia", order_index: 1 },
  { id: "2", name: "Branding", slug: "branding", order_index: 2 },
  { id: "3", name: "Video", slug: "video", order_index: 3 },
];

export const demoProjects: Project[] = [
  {
    id: "demo-1", title: "Luca Pizzeria", slug: "luca-pizzeria",
    description: "Campaña fotográfica gastronómica para Luca Pizzeria. Capturamos la esencia de la cocina italiana con imágenes que despiertan los sentidos.",
    category: "fotografia",
    cover_image_url: "https://picsum.photos/seed/pizza/1200/800", cover_image_id: null,
    images: [
      { id: 1, url: "https://picsum.photos/seed/pizza1/1200/800", thumb: "https://picsum.photos/seed/pizza1/400/300", alt: "Pizza artesanal", width: 1200, height: 800 },
      { id: 2, url: "https://picsum.photos/seed/pizza2/1200/800", thumb: "https://picsum.photos/seed/pizza2/400/300", alt: "Interior del restaurante", width: 1200, height: 800 },
    ],
    video_url: null, client: "Luca Pizzeria", year: "2024", services: ["Fotografía Gastronómica"], featured: true, order_index: 0, created_at: "2024-07-01", updated_at: "2024-07-01",
  },
  {
    id: "demo-2", title: "IVEZ", slug: "ivez",
    description: "Identidad visual completa para IVEZ, una marca de ropa urbana. Diseñamos desde el logotipo hasta la estrategia de redes.",
    category: "branding",
    cover_image_url: "https://picsum.photos/seed/ivez/1200/800", cover_image_id: null,
    images: [
      { id: 3, url: "https://picsum.photos/seed/ivez1/1200/800", thumb: "https://picsum.photos/seed/ivez1/400/300", alt: "Logo IVEZ", width: 1200, height: 800 },
    ],
    video_url: null, client: "IVEZ", year: "2024", services: ["Branding", "Diseño Gráfico"], featured: false, order_index: 1, created_at: "2024-06-15", updated_at: "2024-06-15",
  },
  {
    id: "demo-3", title: "Bomba Frutal", slug: "bomba-frutal",
    description: "Estrategia de social media y contenido visual para Bomba Frutal, una marca de jugos naturales.",
    category: "social-media",
    cover_image_url: "https://picsum.photos/seed/frutal/1200/800", cover_image_id: null,
    images: [
      { id: 4, url: "https://picsum.photos/seed/frutal1/1200/800", thumb: "https://picsum.photos/seed/frutal1/400/300", alt: "Jugo natural", width: 1200, height: 800 },
    ],
    video_url: null, client: "Bomba Frutal", year: "2024", services: ["Social Media", "Fotografía"], featured: false, order_index: 2, created_at: "2024-05-20", updated_at: "2024-05-20",
  },
  {
    id: "demo-4", title: "Universidad para el Futuro", slug: "universidad-para-el-futuro",
    description: "Campaña de branding y comunicación visual para una institución educativa innovadora.",
    category: "branding",
    cover_image_url: "https://picsum.photos/seed/universidad/1200/800", cover_image_id: null,
    images: [
      { id: 5, url: "https://picsum.photos/seed/universidad1/1200/800", thumb: "https://picsum.photos/seed/universidad1/400/300", alt: "Identidad universidad", width: 1200, height: 800 },
    ],
    video_url: null, client: "Universidad para el Futuro", year: "2023", services: ["Branding", "Diseño Web"], featured: false, order_index: 3, created_at: "2023-12-10", updated_at: "2023-12-10",
  },
  {
    id: "demo-5", title: "Fase Matiz", slug: "fase-matiz",
    description: "Producción audiovisual y fotografía de producto para Fase Matiz, una marca de pinturas.",
    category: "video",
    cover_image_url: "https://picsum.photos/seed/matiz/1200/800", cover_image_id: null,
    images: [
      { id: 6, url: "https://picsum.photos/seed/matiz1/1200/800", thumb: "https://picsum.photos/seed/matiz1/400/300", alt: "Producto Fase Matiz", width: 1200, height: 800 },
    ],
    video_url: null, client: "Fase Matiz", year: "2023", services: ["Video", "Fotografía de Producto"], featured: false, order_index: 4, created_at: "2023-11-05", updated_at: "2023-11-05",
  },
  {
    id: "demo-6", title: "Learn To Pic", slug: "learn-to-pic",
    description: "Taller de fotografía. Diseñamos la identidad visual y el material promocional.",
    category: "branding",
    cover_image_url: "https://picsum.photos/seed/learn/1200/800", cover_image_id: null,
    images: [
      { id: 7, url: "https://picsum.photos/seed/learn1/1200/800", thumb: "https://picsum.photos/seed/learn1/400/300", alt: "Learn To Pic branding", width: 1200, height: 800 },
    ],
    video_url: null, client: "Learn To Pic", year: "2023", services: ["Branding", "Diseño Gráfico"], featured: false, order_index: 5, created_at: "2023-10-01", updated_at: "2023-10-01",
  },
  {
    id: "demo-7", title: "Maki", slug: "maki",
    description: "Fotografía gastronómica para el menú de Maki, restaurante de comida asiática.",
    category: "fotografia",
    cover_image_url: "https://picsum.photos/seed/maki/1200/800", cover_image_id: null,
    images: [
      { id: 8, url: "https://picsum.photos/seed/maki1/1200/800", thumb: "https://picsum.photos/seed/maki1/400/300", alt: "Sushi Maki", width: 1200, height: 800 },
    ],
    video_url: null, client: "Maki Sushi", year: "2023", services: ["Fotografía Gastronómica"], featured: false, order_index: 6, created_at: "2023-08-15", updated_at: "2023-08-15",
  },
];

export const demoHeroSlides = [
  {
    image_url: "https://picsum.photos/seed/biyum1/1920/1080",
    title: "Fotografía Publicitaria",
    subtitle: "Destaca tu marca con imágenes que hablan por sí solas.",
    cta_text: "Escríbenos",
    cta_link: "https://wa.me/message/N3PW46LKUALOK1",
  },
  {
    image_url: "https://img.youtube.com/vi/qyjZxlPQSZI/hqdefault.jpg",
    title: "Video Documental",
    subtitle: "Historias reales que conectan con tu audiencia.",
    cta_text: "Ver Video",
    cta_link: "/#video",
    video_id: "qyjZxlPQSZI",
    is_video: true,
    video_start: 10,
  },
  {
    image_url: "https://picsum.photos/seed/biyum3/1920/1080",
    title: "Branding & Diseño",
    subtitle: "Creamos identidades visuales que conectan.",
    cta_text: "Ver Portafolio",
    cta_link: "/#portafolio",
  },
  {
    image_url: "https://img.youtube.com/vi/3u6JWwtC0vE/hqdefault.jpg",
    title: "Producción Cinemática",
    subtitle: "Calidad de cine para tu marca.",
    cta_text: "Ver Video",
    cta_link: "/#video",
    video_id: "3u6JWwtC0vE",
    is_video: true,
    video_start: 10,
  },
  {
    image_url: "https://img.youtube.com/vi/SdcZdfb-na4/hqdefault.jpg",
    title: "Videos Musicales",
    subtitle: "Videoclips que hacen vibrar a tu audiencia.",
    cta_text: "Ver Video",
    cta_link: "/#video",
    video_id: "SdcZdfb-na4",
    is_video: true,
    video_start: 10,
  },
  {
    image_url: "https://img.youtube.com/vi/pwWVLN0QHA4/hqdefault.jpg",
    title: "Documental: Sisay Pacha",
    subtitle: "Celebración ancestral andina del florecimiento.",
    cta_text: "Ver Video",
    cta_link: "/#video",
    video_id: "pwWVLN0QHA4",
    is_video: true,
    video_start: 10,
  },
  {
    image_url: "https://img.youtube.com/vi/t4OQGPbx2t4/hqdefault.jpg",
    title: "Sesiones en Vivo",
    subtitle: "La Perinola Live — música en directo.",
    cta_text: "Ver Video",
    cta_link: "/#video",
    video_id: "t4OQGPbx2t4",
    is_video: true,
    video_start: 10,
  },
];

export const demoVideos = [
  {
    id: "vid-1",
    title: "Documental: Chambo Pobre y Fecundo",
    description: "Explora la realidad de Chambo y los tradicionales ladrilleros.",
    youtubeId: "qyjZxlPQSZI",
    category: "Documental / Storytelling",
  },
  {
    id: "vid-2",
    title: "Sisay Pacha - Fiesta del Carnaval y el Florecimiento",
    description: "Sisaypacha es una celebración ancestral de los pueblos indígenas andinos.",
    youtubeId: "pwWVLN0QHA4",
    category: "Documental / Storytelling",
  },
  {
    id: "vid-3",
    title: "Lejos del Ruido",
    description: "Cortometraje documental de storytelling.",
    youtubeId: "EGWoMrxsj78",
    category: "Documental / Storytelling",
  },
  {
    id: "vid-4",
    title: "Sony FX30 + Artisans Vision Series 35mm T1.05",
    description: "Prueba cinematográfica con lente anamórfica.",
    youtubeId: "3u6JWwtC0vE",
    category: "Cinemático",
  },
  {
    id: "vid-5",
    title: "Baños: Sony FX30 + Sigma 35mm F1.8",
    description: "Secuencia cinematográfica capturada en Baños.",
    youtubeId: "RELxQpoZqHw",
    category: "Cinemático",
  },
  {
    id: "vid-6",
    title: "Noche de edición (#sonyfx30 + Sigma 35mm F1.4 + Godox ML100BI)",
    description: "Making of cinematográfico de una sesión nocturna.",
    youtubeId: "kaaEF36_yxk",
    category: "Cinemático",
  },
  {
    id: "vid-7",
    title: "Sony FX30 + Artisans Vision Series 35mm T1.05 + Godox ML100Bi (HOT DOGS)",
    description: "Spot cinematográfico para hot dogs.",
    youtubeId: "vHr4l_nJvsg",
    category: "Cinemático",
  },
  {
    id: "vid-8",
    title: "Dune Moon - Tiempo (Video Oficial)",
    description: "Videoclip oficial de Dune Moon.",
    youtubeId: "SdcZdfb-na4",
    category: "Videos Musicales",
  },
  {
    id: "vid-9",
    title: "Pneuma - Bajo Fondo (Video Oficial)",
    description: "Videoclip oficial de Pneuma.",
    youtubeId: "hOxQ91yA2JU",
    category: "Videos Musicales",
  },
  {
    id: "vid-10",
    title: "Mística Viral - Ya No Está (Vídeo Oficial)",
    description: "Videoclip oficial de Mística Viral.",
    youtubeId: "pFrW4NgPETU",
    category: "Videos Musicales",
  },
  {
    id: "vid-11",
    title: "MIENTRAS AÚN SALGA EL SOL - MABE - Feat. Mística Viral (Video Oficial)",
    description: "Videoclip oficial de MABE.",
    youtubeId: "iGTkRVbJjVQ",
    category: "Videos Musicales",
  },
  {
    id: "vid-12",
    title: "Ayrton Cortez - Soltar & Sepultado | La Perinola Live",
    description: "Sesión en vivo desde La Perinola.",
    youtubeId: "t4OQGPbx2t4",
    category: "Sesiones en Vivo",
  },
  {
    id: "vid-13",
    title: "Pneuma en vivo (Magma, Akasha, Somos Fuego)",
    description: "Presentación en vivo de Pneuma.",
    youtubeId: "TkurYzuorMQ",
    category: "Sesiones en Vivo",
  },
  {
    id: "vid-14",
    title: "Jorge Sánchez Paucar - Primeriza - Solaz en Vivo",
    description: "Sesión en vivo en Solaz Estudio.",
    youtubeId: "TD-qgMssd_g",
    category: "Sesiones en Vivo",
  },
  {
    id: "vid-15",
    title: "Lunares - Nana Triste - Solaz en Vivo",
    description: "Sesión en vivo en Solaz Estudio.",
    youtubeId: "WF07hgDGNBk",
    category: "Sesiones en Vivo",
  },
  {
    id: "vid-16",
    title: "Mística Viral - Y Sabes",
    description: "Animación oficial de Mística Viral.",
    youtubeId: "T4RgQ0hq2f8",
    category: "Animaciones",
  },
];
